// Generated by scripts/build_deploy_package.py in the source workspace.
// The app shell is cached per release; audio lives in its own cache keyed by content-hashed
// URLs from tracks.json, so a release that only changes the interface downloads no audio.
const SHELL_CACHE = 'luisterspoor-shell-08764fc7e4';
const MEDIA_CACHE = 'luisterspoor-media';
const SHELL = [
  "./",
  "index.html",
  "tracks.json",
  "manifest.webmanifest",
  "app/core.js",
  "app/icons.js",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/favicon.svg",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/logo.svg",
  "icons/maskable-192.png",
  "icons/maskable-512.png"
];

const scoped = (path) => new URL(path, self.registration.scope).href;

async function mediaUrls() {
  const response = await fetch(scoped('tracks.json'), { cache: 'reload' });
  const index = await response.json();
  const urls = new Set();
  for (const track of index.tracks || []) {
    for (const key of ['audio', 'manifest', 'text_manifest']) {
      if (track[key]) urls.add(scoped(track[key]));
    }
  }
  return [...urls];
}

async function cacheAll(cache, urls) {
  for (const url of urls) {
    const response = await fetch(url, { cache: 'reload' });
    if (!response.ok) throw new Error(`Failed to cache ${url}: ${response.status}`);
    await cache.put(url, response);
  }
}

async function precache() {
  await cacheAll(await caches.open(SHELL_CACHE), SHELL.map(scoped));
  const media = await caches.open(MEDIA_CACHE);
  const missing = [];
  for (const url of await mediaUrls()) {
    if (!(await media.match(url))) missing.push(url);
  }
  await cacheAll(media, missing);
}

async function cleanUp() {
  for (const key of await caches.keys()) {
    if (key.startsWith('luisterspoor-') && key !== SHELL_CACHE && key !== MEDIA_CACHE) await caches.delete(key);
  }
  // Drop audio that tracks.json no longer points to, such as the old version of a rebuilt track.
  const keep = new Set(await mediaUrls());
  const media = await caches.open(MEDIA_CACHE);
  for (const request of await media.keys()) {
    if (!keep.has(request.url)) await media.delete(request);
  }
}

self.addEventListener('install', (event) => {
  event.waitUntil(precache().then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(cleanUp().catch(() => {}).then(() => self.clients.claim()));
});

async function fromCache(url) {
  return (await caches.match(url, { cacheName: SHELL_CACHE })) || caches.match(url, { cacheName: MEDIA_CACHE });
}

// Media elements ask for byte ranges; slicing the cached blob keeps seeking fast offline.
async function rangeResponse(request, response) {
  const match = /bytes=(\d*)-(\d*)/.exec(request.headers.get('range') || '');
  if (!match) return response;
  const blob = await response.blob();
  const size = blob.size;
  let start = Number(match[1] || 0);
  let end = match[2] ? Math.min(Number(match[2]), size - 1) : size - 1;
  if (!match[1] && match[2]) {
    start = Math.max(0, size - Number(match[2]));
    end = size - 1;
  }
  if (start >= size || start > end) {
    return new Response(null, { status: 416, headers: { 'Content-Range': `bytes */${size}` } });
  }
  return new Response(blob.slice(start, end + 1), {
    status: 206,
    statusText: 'Partial Content',
    headers: {
      'Content-Type': response.headers.get('Content-Type') || 'audio/mpeg',
      'Content-Length': String(end - start + 1),
      'Content-Range': `bytes ${start}-${end}/${size}`,
      'Accept-Ranges': 'bytes',
    },
  });
}

async function respond(request) {
  if (request.mode === 'navigate') {
    return (await fromCache(scoped('index.html'))) || fetch(request);
  }
  const cached = await fromCache(request.url);
  if (cached) return request.headers.has('range') ? rangeResponse(request, cached) : cached;
  return fetch(request);
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== location.origin) return;
  event.respondWith(respond(request));
});
